version: '3.7'

services:
  web:
    container_name: nest-web
    build:
      context: .
      target: ${BUILD_ENV}
    restart: always
    volumes:
      - .:/usr/src/nest-boilerplate
      - /usr/src/nest-boilerplate/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - webnet
    depends_on:
      - postgres
  postgres:
    container_name: nest-postgres
    image: postgres:13.1
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/nest-postgresql/data
    ports:
      - 5435:5435
    expose:
      - 5435
    command: -p 5435
    volumes:
      - pgdata:/var/lib/nest-postgresql/data
networks:
  webnet:
volumes:
  pgdata: